### ISSUE TITLE
Tar files corrupted

### ISSUE THREAD

**Issue by pranayreddys** [akhilmathurs/libriadapt#1]
The tar files for British and Indian accents seem to be corrupted, they are not getting extracted properly.

**Comment by x4d-friends** [comment]
Hi, I could not replicate the issue. Can you please tell what errors do you get? 

The tar files need to be merged before extracting them, as explained here https://github.com/akhilmathurs/libriadapt#merge-the-targzpart_-files

**Comment by akhilmathurs** [comment]
Hi, I could not replicate the issue. Can you please tell what errors do you get?

The tar files need to be merged before extracting them, as explained here https://github.com/akhilmathurs/libriadapt#merge-the-targzpart_-files

**Comment by pranayreddys** [comment]
Thank you for pointing out the command, I missed it.
