### ISSUE TITLE
Any recipe using ESPNet?

### ISSUE THREAD

**Issue by jindongwang** [akhilmathurs/libriadapt#2]
This dataset is really useful. Is there any recipe using ESPNet to extract features?

**Comment by akhilmathurs** [comment]
Hi, we do not provide any code for feature extraction. The dataset contains .wav files at 16khz and they should be compatible with any available feature extraction toolkit. For our evaluation, we used the feature extraction code from Mozilla DeepSpeech2 to generate melspectrograms and MFCCs.
