### ISSUE TITLE
download link unavailable

### ISSUE THREAD

**Issue by yuexianghubit** [akhilmathurs/libriadapt#6]
Hi, thanks for your nice dataset.

Now it seems all the download links are not valid. Could you please help check the reason?

This dataset is the only one that I know of that fits my domain shift on ASR tasks.
Thanks!

**Comment by akhilmathurs** [comment]
Thanks for pointing it out. Our hosting website has gone down -- we are looking into it and will update the links once the website issue is fixed.

**Comment by akhilmathurs** [comment]
@yuexianghubit, the website is back up and the issue is fixed now.
